### ISSUE TITLE
vTHL3: Copy existing form as the base for new form

### ISSUE THREAD

**Issue by foxlynx** [CSCfi/rems#977] opened 2019-02-28 07:41 UTC
Customer wants to make new forms based on existing form. Related to issue: https://github.com/CSCfi/rems/issues/865 but this is simpler to implement and was wished by the customer.

**Comment by opqdonut** [comment] 2019-05-02 06:01
this is a duplicate of #836

**Closed by opqdonut** 2019-05-02 06:01 UTC
