### ISSUE TITLE
Email poller gets stuck in a loop if one of target email addresses does not work

### ISSUE THREAD

**Issue by okahilak** [CSCfi/rems#1750] opened 2019-10-31 14:36 UTC
... resending email to all the previous target addresses.

Consider a retry limit or some other way to not re-send to those addresses that have already been sent to.

**Comment by Macroz** [comment] 2019-10-31 16:28
@okahilak this looks like a duplicate of #1026?

**Comment by opqdonut** [comment] 2019-11-01 06:17
One additional detail is that it seems our workaround
```
(catch SMTPAddressFailedException e ; email address does not exist
```
is not working because the `SMTPAddressFailedException` is wrapped inside a `javax.mail.SendFailedException: Invalid Addresses`

**Comment by opqdonut** [comment] 2019-11-05 12:45
Discussed this with @luontola. Let's try to replace the event pollers with queues. We can use a process manager (like the approver bot) to insert emails and entitlements into queues (database tables). These queues would then have pollers that would perform email sending and entitlement POSTing (with retry, backoff, etc.).

**Comment by opqdonut** [comment] 2019-11-05 12:56
perhaps "outbox" instead of "queue", no need to have FIFO semantics

**Closed** 2019-11-12 07:28 UTC
Labels: BUG
