### ISSUE TITLE
Make sorting in tables case-insensitive

### ISSUE THREAD

**Issue by okahilak** [CSCfi/rems#1526] opened 2019-08-22 10:08 UTC

**Comment by aatkin** [comment] 2022-05-18 15:43
this enhancement needs more details, maybe reproduction of the issue. current table implementation seems to treat sorting case-insensitively?

**Comment by Macroz** [comment] 2022-05-23 08:05
Fixed already in #1551. Duplicate of #1527.

**Closed by Macroz** 2022-05-23 08:05 UTC
Labels: Enhancement, Easy
