### ISSUE TITLE
Display selected applicant's OIDC claims in UI for handler

### ISSUE THREAD

**Issue by jaakkocsc** [CSCfi/rems#2241] opened 2020-06-17 06:36 UTC
Handler UI should display selected OIDC claims returned by the OP. Selection could be static in config or configurable in admin UI.

**Comment by opqdonut** [comment] 2020-08-20 10:41
duplicate of #2130 ?

**Comment by opqdonut** [comment] 2020-08-27 10:03
possible after #2130

**Closed by opqdonut** 2020-08-27 10:03 UTC
Labels: Findata
