### ISSUE TITLE
Search field does not show results until non-empty

### ISSUE THREAD

**Issue by okahilak** [CSCfi/rems#1493] opened 2019-08-15 07:12 UTC
As reported by NKR's Hannu:

RDapprover1 user does not see any open applications until something is written on the search field that matches an application:

![image](https://user-images.githubusercontent.com/49641103/63078699-0b9d0800-bf45-11e9-90eb-8635624fc868.png)

After filling out the field:

![image](https://user-images.githubusercontent.com/49641103/63078749-35562f00-bf45-11e9-918e-8098d26d3867.png)

**Comment by opqdonut** [comment] 2019-08-15 07:15
Can't reproduce on my machine using test-data. Might need to debug in the NKR environment. Does the frontend query for all applications? Does the query fail?

**Comment by opqdonut** [comment] 2019-08-15 07:27
Ah, the `applications/todo` endpoint returns 500 because an applicant is missing user attrs.

**Comment by opqdonut** [comment] 2019-08-15 11:31
The problem was fixed in NKR by adding the missing user to the db. Additionally, #1497 adds error handling for search.

**Comment by opqdonut** [comment] 2019-08-15 12:54
Let's call this done for now

**Closed by opqdonut** 2019-08-15 12:54 UTC
